"""remove unused user_company_access table

Revision ID: 1098e4c11995
Revises: fc2bfe64c28f
Create Date: 2026-07-13 12:50:36.465913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1098e4c11995'
down_revision: Union[str, Sequence[str], None] = 'fc2bfe64c28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
