"""remove unused user_company_access table

Revision ID: 4d140f3671b9
Revises: 1098e4c11995
Create Date: 2026-07-13 12:51:21.112698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d140f3671b9'
down_revision: Union[str, Sequence[str], None] = '1098e4c11995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_company_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_company_access',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_company_access_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'company_code', name=op.f('user_company_access_pkey'))
    )
    # ### end Alembic commands ###
